from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import render

personal_info = {
    "name": "Shashi Bhagat",
    "mobile_no": "9931920057",
    "address": {
        "village": "Ghaghra",
        "post": "Ghaghra",
        "dist": "Ghaghra",
        "pincode": 835208
    }
}

country_obj = {
    'Afghanistan': {'code': 'AF'},
    'Åland Islands': {'code': 'AX'},
    'Albania': {'code': 'AL'},
    'Algeria': {'code': 'DZ'},
    'American Samoa': {'code': 'AS'},
    'AndorrA': {'code': 'AD'},
    'Angola': {'code': 'AO'},
    'Anguilla': {'code': 'AI'},
    'Antarctica': {'code': 'AQ'},
    'Antigua and Barbuda': {'code': 'AG'},
    'Argentina': {'code': 'AR'},
    'Armenia': {'code': 'AM'},
    'Aruba': {'code': 'AW'},
    'Australia': {'code': 'AU'},
    'Austria': {'code': 'AT'},
    'Azerbaijan': {'code': 'AZ'},
    'Bahamas': {'code': 'BS'},
    'Bahrain': {'code': 'BH'},
    'Bangladesh': {'code': 'BD'},
    'Barbados': {'code': 'BB'},
    'Belarus': {'code': 'BY'},
    'Belgium': {'code': 'BE'},
    'Belize': {'code': 'BZ'},
    'Benin': {'code': 'BJ'},
    'Bermuda': {'code': 'BM'},
    'Bhutan': {'code': 'BT'},
    'Bolivia': {'code': 'BO'},
    'Bosnia and Herzegovina': {'code': 'BA'},
    'Botswana': {'code': 'BW'},
    'Bouvet Island': {'code': 'BV'},
    'Brazil': {'code': 'BR'},
    'British Indian Ocean Territory': {'code': 'IO'},
    'Brunei Darussalam': {'code': 'BN'},
    'Bulgaria': {'code': 'BG'},
    'Burkina Faso': {'code': 'BF'},
    'Burundi': {'code': 'BI'},
    'Cambodia': {'code': 'KH'},
    'Cameroon': {'code': 'CM'},
    'Canada': {'code': 'CA'},
    'Cape Verde': {'code': 'CV'},
    'Cayman Islands': {'code': 'KY'},
    'Central African Republic': {'code': 'CF'},
    'Chad': {'code': 'TD'},
    'Chile': {'code': 'CL'},
    'China': {'code': 'CN'},
    'Christmas Island': {'code': 'CX'},
    'Cocos (Keeling) Islands': {'code': 'CC'},
    'Colombia': {'code': 'CO'},
    'Comoros': {'code': 'KM'},
    'Congo': {'code': 'CG'},
    'Congo, The Democratic Republic of the': {'code': 'CD'},
    'Cook Islands': {'code': 'CK'},
    'Costa Rica': {'code': 'CR'},
    "Cote D'Ivoire": {'code': 'CI'},
    'Croatia': {'code': 'HR'},
    'Cuba': {'code': 'CU'},
    'Cyprus': {'code': 'CY'},
    'Czech Republic': {'code': 'CZ'},
    'Denmark': {'code': 'DK'},
    'Djibouti': {'code': 'DJ'},
    'Dominica': {'code': 'DM'},
    'Dominican Republic': {'code': 'DO'},
    'Ecuador': {'code': 'EC'},
    'Egypt': {'code': 'EG'},
    'El Salvador': {'code': 'SV'},
    'Equatorial Guinea': {'code': 'GQ'},
    'Eritrea': {'code': 'ER'},
    'Estonia': {'code': 'EE'},
    'Ethiopia': {'code': 'ET'},
    'Falkland Islands (Malvinas)': {'code': 'FK'},
    'Faroe Islands': {'code': 'FO'},
    'Fiji': {'code': 'FJ'},
    'Finland': {'code': 'FI'},
    'France': {'code': 'FR'},
    'French Guiana': {'code': 'GF'},
    'French Polynesia': {'code': 'PF'},
    'French Southern Territories': {'code': 'TF'},
    'Gabon': {'code': 'GA'},
    'Gambia': {'code': 'GM'},
    'Georgia': {'code': 'GE'},
    'Germany': {'code': 'DE'},
    'Ghana': {'code': 'GH'},
    'Gibraltar': {'code': 'GI'},
    'Greece': {'code': 'GR'},
    'Greenland': {'code': 'GL'},
    'Grenada': {'code': 'GD'},
    'Guadeloupe': {'code': 'GP'},
    'Guam': {'code': 'GU'},
    'Guatemala': {'code': 'GT'},
    'Guernsey': {'code': 'GG'},
    'Guinea': {'code': 'GN'},
    'Guinea-Bissau': {'code': 'GW'},
    'Guyana': {'code': 'GY'},
    'Haiti': {'code': 'HT'},
    'Heard Island and Mcdonald Islands': {'code': 'HM'},
    'Holy See (Vatican City State)': {'code': 'VA'},
    'Honduras': {'code': 'HN'},
    'Hong Kong': {'code': 'HK'},
    'Hungary': {'code': 'HU'},
    'Iceland': {'code': 'IS'},
    'India': {'code': 'IN'},
    'Indonesia': {'code': 'ID'},
    'Iran, Islamic Republic Of': {'code': 'IR'},
    'Iraq': {'code': 'IQ'},
    'Ireland': {'code': 'IE'},
    'Isle of Man': {'code': 'IM'},
    'Israel': {'code': 'IL'},
    'Italy': {'code': 'IT'},
    'Jamaica': {'code': 'JM'},
    'Japan': {'code': 'JP'},
    'Jersey': {'code': 'JE'},
    'Jordan': {'code': 'JO'},
    'Kazakhstan': {'code': 'KZ'},
    'Kenya': {'code': 'KE'},
    'Kiribati': {'code': 'KI'},
    "Korea, Democratic People'S Republic of": {'code': 'KP'},
    'Korea, Republic of': {'code': 'KR'},
    'Kuwait': {'code': 'KW'},
    'Kyrgyzstan': {'code': 'KG'},
    "Lao People'S Democratic Republic": {'code': 'LA'},
    'Latvia': {'code': 'LV'},
    'Lebanon': {'code': 'LB'},
    'Lesotho': {'code': 'LS'},
    'Liberia': {'code': 'LR'},
    'Libyan Arab Jamahiriya': {'code': 'LY'},
    'Liechtenstein': {'code': 'LI'},
    'Lithuania': {'code': 'LT'},
    'Luxembourg': {'code': 'LU'},
    'Macao': {'code': 'MO'},
    'Macedonia, The Former Yugoslav Republic of': {'code': 'MK'},
    'Madagascar': {'code': 'MG'},
    'Malawi': {'code': 'MW'},
    'Malaysia': {'code': 'MY'},
    'Maldives': {'code': 'MV'},
    'Mali': {'code': 'ML'},
    'Malta': {'code': 'MT'},
    'Marshall Islands': {'code': 'MH'},
    'Martinique': {'code': 'MQ'},
    'Mauritania': {'code': 'MR'},
    'Mauritius': {'code': 'MU'},
    'Mayotte': {'code': 'YT'},
    'Mexico': {'code': 'MX'},
    'Micronesia, Federated States of': {'code': 'FM'},
    'Moldova, Republic of': {'code': 'MD'},
    'Monaco': {'code': 'MC'},
    'Mongolia': {'code': 'MN'},
    'Montserrat': {'code': 'MS'},
    'Morocco': {'code': 'MA'},
    'Mozambique': {'code': 'MZ'},
    'Myanmar': {'code': 'MM'},
    'Namibia': {'code': 'NA'},
    'Nauru': {'code': 'NR'},
    'Nepal': {'code': 'NP'},
    'Netherlands': {'code': 'NL'},
    'Netherlands Antilles': {'code': 'AN'},
    'New Caledonia': {'code': 'NC'},
    'New Zealand': {'code': 'NZ'},
    'Nicaragua': {'code': 'NI'},
    'Niger': {'code': 'NE'},
    'Nigeria': {'code': 'NG'},
    'Niue': {'code': 'NU'},
    'Norfolk Island': {'code': 'NF'},
    'Northern Mariana Islands': {'code': 'MP'},
    'Norway': {'code': 'NO'},
    'Oman': {'code': 'OM'},
    'Pakistan': {'code': 'PK'},
    'Palau': {'code': 'PW'},
    'Palestinian Territory, Occupied': {'code': 'PS'},
    'Panama': {'code': 'PA'},
    'Papua New Guinea': {'code': 'PG'},
    'Paraguay': {'code': 'PY'},
    'Peru': {'code': 'PE'},
    'Philippines': {'code': 'PH'},
    'Pitcairn': {'code': 'PN'},
    'Poland': {'code': 'PL'},
    'Portugal': {'code': 'PT'},
    'Puerto Rico': {'code': 'PR'},
    'Qatar': {'code': 'QA'},
    'Reunion': {'code': 'RE'},
    'Romania': {'code': 'RO'},
    'Russian Federation': {'code': 'RU'},
    'RWANDA': {'code': 'RW'},
    'Saint Helena': {'code': 'SH'},
    'Saint Kitts and Nevis': {'code': 'KN'},
    'Saint Lucia': {'code': 'LC'},
    'Saint Pierre and Miquelon': {'code': 'PM'},
    'Saint Vincent and the Grenadines': {'code': 'VC'},
    'Samoa': {'code': 'WS'},
    'San Marino': {'code': 'SM'},
    'Sao Tome and Principe': {'code': 'ST'},
    'Saudi Arabia': {'code': 'SA'},
    'Senegal': {'code': 'SN'},
    'Serbia and Montenegro': {'code': 'CS'},
    'Seychelles': {'code': 'SC'},
    'Sierra Leone': {'code': 'SL'},
    'Singapore': {'code': 'SG'},
    'Slovakia': {'code': 'SK'},
    'Slovenia': {'code': 'SI'},
    'Solomon Islands': {'code': 'SB'},
    'Somalia': {'code': 'SO'},
    'South Africa': {'code': 'ZA'},
    'South Georgia and the South Sandwich Islands': {'code': 'GS'},
    'Spain': {'code': 'ES'},
    'Sri Lanka': {'code': 'LK'},
    'Sudan': {'code': 'SD'},
    'Suriname': {'code': 'SR'},
    'Svalbard and Jan Mayen': {'code': 'SJ'},
    'Swaziland': {'code': 'SZ'},
    'Sweden': {'code': 'SE'},
    'Switzerland': {'code': 'CH'},
    'Syrian Arab Republic': {'code': 'SY'},
    'Taiwan, Province of China': {'code': 'TW'},
    'Tajikistan': {'code': 'TJ'},
    'Tanzania, United Republic of': {'code': 'TZ'},
    'Thailand': {'code': 'TH'},
    'Timor-Leste': {'code': 'TL'},
    'Togo': {'code': 'TG'},
    'Tokelau': {'code': 'TK'},
    'Tonga': {'code': 'TO'},
    'Trinidad and Tobago': {'code': 'TT'},
    'Tunisia': {'code': 'TN'},
    'Turkey': {'code': 'TR'},
    'Turkmenistan': {'code': 'TM'},
    'Turks and Caicos Islands': {'code': 'TC'},
    'Tuvalu': {'code': 'TV'},
    'Uganda': {'code': 'UG'},
    'Ukraine': {'code': 'UA'},
    'United Arab Emirates': {'code': 'AE'},
    'United Kingdom': {'code': 'GB'},
    'United States': {'code': 'US'},
    'United States Minor Outlying Islands': {'code': 'UM'},
    'Uruguay': {'code': 'UY'},
    'Uzbekistan': {'code': 'UZ'},
    'Vanuatu': {'code': 'VU'},
    'Venezuela': {'code': 'VE'},
    'Viet Nam': {'code': 'VN'},
    'Virgin Islands, British': {'code': 'VG'},
    'Virgin Islands, U.S.': {'code': 'VI'},
    'Wallis and Futuna': {'code': 'WF'},
    'Western Sahara': {'code': 'EH'},
    'Yemen': {'code': 'YE'},
    'Zambia': {'code': 'ZM'},
    'Zimbabwe': {'code': 'ZW'},
    }
# Create your views here.


def landing_page(request):
    return render(request, 'index.html')


def about_page(request):
    # return HttpResponse('Hi! I am Shashi Bhushan Bhagat')
    return render(request, 'aboutUs.html', personal_info)


def services_page(request):
    return HttpResponse('<b>We have several sevices, you just have to ask what</b>')


def blog(request):
    return render(request, 'blog.html')


def fetch_info(request, info):
    if info in personal_info:
        info_fetched = personal_info[info]
        if isinstance(info_fetched, dict):
            return JsonResponse(info_fetched)

        return HttpResponse(info_fetched)
    else:
        return HttpResponseNotFound(f"Invalid request {info}")
    

def find_country_code(request, country):
    if country in country_obj:
        return JsonResponse(country_obj[country])
    return HttpResponseNotFound("Invalid country name or miss spelled")
